# Generated by Django 4.1.4 on 2022-12-09 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0003_alter_profile_created_alter_profile_f_fin_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="f_fin",),
        migrations.AddField(
            model_name="profile", name="days", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 8, 19, 16, 153371)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="f_inicio",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 8, 19, 16, 153371)
            ),
        ),
    ]
