# Generated by Django 4.1.4 on 2022-12-09 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0004_remove_profile_f_fin_profile_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 8, 27, 20, 365770)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 8, 27, 20, 365770)
            ),
        ),
    ]
