# Generated by Django 4.1.4 on 2022-12-09 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0007_alter_profile_created_alter_profile_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 8, 29, 37, 204622)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="f_inicio",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2022, 12, 9, 8, 29, 37, 204622)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 8, 29, 37, 204622)
            ),
        ),
    ]
