# Generated by Django 4.1.4 on 2022-12-12 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0010_alter_profile_created_alter_profile_f_inicio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Nombre clave"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Red social")),
                ("url", models.URLField(blank=True, null=True, verbose_name="Enlace")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "enlace",
                "verbose_name_plural": "enlaces",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 12, 16, 33, 23, 320039)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="f_inicio",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 12, 16, 33, 23, 320039)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 12, 16, 33, 23, 320039)
            ),
        ),
    ]
