# Generated by Django 4.1.4 on 2022-12-12 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "principal",
            "0011_link_alter_profile_created_alter_profile_f_inicio_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="Link",),
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 12, 16, 46, 51, 794999)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="f_inicio",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 12, 16, 46, 51, 794999)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 12, 16, 46, 51, 794999)
            ),
        ),
    ]
