booleano = True
entero = 2345
flotante = 342.32
complejo = 3+5j
cadena = 'yutres'
tupla = (1, 4, 5, 2, 7)
lista = ['pera', 'mansza', 5, 'yo', 3.4]
conjunto = set([2,4,6,8])
diccionario = {
    'firefox': 'v8',
    'chrome': 'v6',
    'js': '3'
}
print(abs())
print(all())
print(any())
print(ascii())
print(bin())
print(bool())
print(breakpoint())
print(bytearray())
print(bytes())
print(callable())
print(chr())
print(classmethod())
print(compile())
print(complex())
print(delattr())
print(dict())
print(any())
print(divmod())
print(enumerate())
print(eval())
print(exec())
print(filter())
print(float())
print(format())
print(frozenset())
print(getattr())
print(globals())
print(hasattr())
print(hash())
print(help())
print(hex())
print(id())
print(input())
print(int())
print(isinstance())
print(issubclass())
print(iter())
print(len())
print(list())
print(locals())
print(map())
print(max())
print(memoryview())
print(min())
print(next())
print(object())
print(oct())
print(open())
print(ord())
print(pow())
print(print())
print(property())
print(range())
print(repr())
print(reversed())
print(round())
print(set())
print(setattr())
print(slice())
print(sorted())
print(staticmethod())
print(str())
print(sum())
print(super(tupla))
print(tuple())
print(type())
print(vars())
print(zip())
print(__import__())